
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwThLy9Cu1vrJ55BnGS-kL2aYm-4tddmM',
    appId: '1:554398395959:web:cfd9f4e7fbad7e9a7a19b2',
    messagingSenderId: '554398395959',
    projectId: 'ume123-cad6f',
    authDomain: 'ume123-cad6f.firebaseapp.com',
    storageBucket: 'ume123-cad6f.appspot.com',
    measurementId: 'G-LBRLC8LMT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRqWOYg_5DKDGABzj90Y-WBpt-NdwuE0',
    appId: '1:554398395959:android:1f91946201934eb97a19b2',
    messagingSenderId: '554398395959',
    projectId: 'ume123-cad6f',
    storageBucket: 'ume123-cad6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCT81RAQYJeyBaDU5gGoX072GKHVG3F0',
    appId: '1:554398395959:ios:ca1777d3d1aa9afb7a19b2',
    messagingSenderId: '554398395959',
    projectId: 'ume123-cad6f',
    storageBucket: 'ume123-cad6f.appspot.com',
    iosBundleId: 'com.example.appUmiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjCT81RAQYJeyBaDU5gGoX072GKHVG3F0',
    appId: '1:554398395959:ios:ca1777d3d1aa9afb7a19b2',
    messagingSenderId: '554398395959',
    projectId: 'ume123-cad6f',
    storageBucket: 'ume123-cad6f.appspot.com',
    iosBundleId: 'com.example.appUmiTest',
  );
}
